### ISSUE TITLE
Criar página para documentação - GitHub Page

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar-Usuario#55]
### Descrição:
Criar e organizar em uma branch, uma GitHub Page para a disponibilização da documentação do projeto.

### Tarefas:

- [x]  Criar uma branch para ser a fonte da página.

- [x] Mover a pasta docs para a nova branch.

- [x] Atualizar o repositório.

### Critérios de aceitação:

- [x] A página deve estar acessível de forma funcional.

**Comment by Bruno-Felix** [comment]
Como a issue de criação da gh page está sendo feita nessa sprint, irei colocar a label de gh page nos documentos que precisam estar na página.
- #58 
- #59

**Comment by Bruno-Felix** [comment]
Sugiro não apagar a pasta docs até o final da sprint. Muitos documentos estão sendo desenvolvidos nesse momento nessa pasta.

Apaga-la antes de tudo ser feito gerará graves conflitos no repositório.

**Comment by DanielPortods** [comment]
Foi criada uma nova branch chamada gh-page para fins de hospedagem da página de documentação. Como sugerido pelo @Bruno-Felix , por hora não será excluída a pasta docs da branch develop para evitar conflitos com o desenvolvimento atual dos documentos.

**Comment by DanielPortods** [comment]
A GitHub page da documentação do projeto pode ser acessada por [aqui](https://fga-eps-mds.github.io/2020.1-Vamos_Cuidar-Usuario/#/).

**Comment by DanielPortods** [comment]
A GitHub page de documentação do projeto pode ser acessada por [aqui](https://fga-eps-mds.github.io/2020.1-Vamos_Cuidar-Usuario/#/).
