### ISSUE TITLE
Revisar Contributing

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2020.1-Vamos_Cuidar-Usuario#62]
### Descrição:
Issue destinada a revisão do Contributing.
### Tarefas:

- [x] Visualização de grupos anteriores;
- [x] Colocar a opção de documentos no template de Pull Request.

### Critérios de aceitação:

- [x] Opção de Documentos adicionado ao template de Pull Request;
- [x] Ter visto o Contributing de grupos anteriores.

**Comment by Bruno-Felix** [comment]
Isso já trabalhada mas não modificada no workflow do zenHub, ainda como New issue.

**Comment by enzoggqs** [comment]
Todos os critérios de aceitação foram atingidos, por isso a issue será fechada.
