### ISSUE TITLE
Desenvolver protótipo de baixa fidelidade 

### ISSUE THREAD

**Issue by DanielPortods** [fga-eps-mds/2020.1-Vamos_Cuidar-Usuario#67]
### Descrição:
Criar um protótipo de baixa fidelidade da plataforma.

### Tarefas:

- [x] Criar telas para perfil do usuário.

- [x] Criar telas para o feed.

- [x] Criar telas para notícias.

- [x] Criar telas para postagem.

- [x] Criar telas para login.

### Critérios de aceitação:

- [x] Todos os requisitos funcionais devem ser contemplados no protótipo.

- [x] Realizar reuniões para discutir as tarefas e analisar os resultados.

- [x] Mobile first!

- [x] Criar issue de Desenvolver protótipo de alta fidelidade

**Comment by DanielPortods** [comment]
Foi marcada a reunião de desenvolvimento do protótipo para o dia 19/09 às 19 horas.

**Comment by emysdias** [comment]
#67 Modelos de protótipo
![photo5125218649827813584](https://user-images.githubusercontent.com/52640974/93532490-80483000-f917-11ea-90b3-f6cd2e00fff1.jpg)

![photo5125218649827813585](https://user-images.githubusercontent.com/52640974/93532510-8a6a2e80-f917-11ea-85ed-2917bc13fd6a.jpg)

![photo5125218649827813586](https://user-images.githubusercontent.com/52640974/93532523-90f8a600-f917-11ea-9f25-d57e704208d7.jpg)

**Comment by DanielPortods** [comment]
### Algumas telas
![IMG_20200918_073910292](https://user-images.githubusercontent.com/48573556/93589436-2da45d80-f983-11ea-9113-25426a9f8e0e.jpg)
![IMG_20200918_073923086](https://user-images.githubusercontent.com/48573556/93589521-4b71c280-f983-11ea-8f38-bad52a0acc11.jpg)
![IMG_20200918_073934716](https://user-images.githubusercontent.com/48573556/93589595-67756400-f983-11ea-9593-b050fafb6901.jpg)
![IMG_20200918_073944781](https://user-images.githubusercontent.com/48573556/93589608-6d6b4500-f983-11ea-9f6e-69e66dcd0acc.jpg)

**Comment by enzoggqs** [comment]
![IMG_20200918_171027_885.jpg](https://user-images.githubusercontent.com/38733364/93641073-117bdd00-f9d2-11ea-87d8-5e9b67b75e7f.jpg)

**Comment by enzoggqs** [comment]
![IMG_20200918_171038_279.jpg](https://user-images.githubusercontent.com/38733364/93641110-1d679f00-f9d2-11ea-8f5e-3cb5eee4b54c.jpg)

**Comment by enzoggqs** [comment]
![IMG_20200918_171044_683.jpg](https://user-images.githubusercontent.com/38733364/93641134-26f10700-f9d2-11ea-9740-673f975b27d4.jpg)

**Comment by enzoggqs** [comment]
![IMG_20200918_171052_273.jpg](https://user-images.githubusercontent.com/38733364/93641144-2e181500-f9d2-11ea-85b6-40614be04852.jpg)

**Comment by daniel-bm** [comment]
![b848ff63-405f-4cd3-888d-7908fe974c5e](https://user-images.githubusercontent.com/38585724/93644623-c31e0c80-f9d8-11ea-92d7-2b5c7960de56.jpeg)
![98437ca7-2d80-4e08-b617-4f8c056abae5](https://user-images.githubusercontent.com/38585724/93644649-cc0ede00-f9d8-11ea-8920-f9f0a110e3c0.jpeg)

**Comment by Bruno-Felix** [comment]
Minha visão de protótipo da aplicação:

[Prototipo_Vamos Cuidar.pdf](https://github.com/fga-eps-mds/2020.1-Vamos_Cuidar-Usuario/files/5248153/Prototipo_Vamos.Cuidar.pdf)

**Comment by Bruno-Felix** [comment]
![Captura de tela de 2020-09-18 19-34-48](https://user-images.githubusercontent.com/38890440/93650909-2498a800-f9e6-11ea-90e8-3e70adc33ea0.png)

**Comment by DanielPortods** [comment]
Foi realizada a reunião hoje e todos os integrantes participaram do desenvolvimento do protótipo pela plataforma miro.

**Comment by Bruno-Felix** [comment]
![Captura de tela de 2020-09-18 23-08-04](https://user-images.githubusercontent.com/38890440/93656846-db575100-fa03-11ea-8f20-a4654730045c.png)
![Captura de tela de 2020-09-18 23-02-50](https://user-images.githubusercontent.com/38890440/93656770-389ed280-fa03-11ea-8fc4-11637d94d2a0.png)
![Captura de tela de 2020-09-18 23-02-23](https://user-images.githubusercontent.com/38890440/93656771-39376900-fa03-11ea-97ee-955cb044ee8b.png)
![Captura de tela de 2020-09-18 23-03-14](https://user-images.githubusercontent.com/38890440/93656769-376da580-fa03-11ea-9dad-7bbab5665025.png)

**Comment by Bruno-Felix** [comment]
Faltou esses Requisitos:
- Falta sair da conta

**Comment by Bruno-Felix** [comment]
Talvez seja preciso uma serif para textos: Peddana
