### ISSUE TITLE
Reunião com grupo Dashboard

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2020.1-Vamos_Cuidar-Usuario#70]
Reunião com grupo Dashboard

### Descrição:
Issue destinada a reunião com o grupo responsável pela parte do Dashboard da aplicação.

### Tarefas:
- Alinhar a visão de produto que cada grupo tem;
- Debater questões de requisitos, feactures e backlog do produto;
- Conversar sobre questões de arquitetura e troca de dados;
- Conversar sobre questões de identidade visual;
- Debater a necessidade de reuniões a cada x sprints.

### Critérios de aceitação:
- [x] Dois grupos alinharem suas visões sobre o que deve ser o produto.
- [x] Dois grupos alinharem ordem de prioridade e funcionalidades do produto;
- [ ] Dois grupos chegarem a uma data interessante para reuniões.

**Comment by Bruno-Felix** [comment]
Reunião Marcada para hoje, dia 14/09, as 19:30h

**Comment by DenysRogeres** [comment]
Fomos na reunião com os dois EPS do outro grupo e compartilhamos bastante coisa, deu pra dar um norteamento para onde seguir, contudo, acredito que ainda exista alguns pontos que não foram totalmente esclarecidos.

**Comment by Bruno-Felix** [comment]
Grupo Dashboard enviou os dados (em verde) que eles necessitam no produto deles:

![photo5118826900972742803](https://user-images.githubusercontent.com/38890440/93305522-fee88480-f7d4-11ea-926a-33b5f0764cd4.jpg)

**Comment by Bruno-Felix** [comment]
Ainda falta conversar melhor sobre várias coisa. Como por exemplo sobre a possibilidade de uma reunião a cada x dias para debatermos o andamento dos 2 projetos.

**Comment by Bruno-Felix** [comment]
![Captura de tela de 2020-09-18 23-08-04](https://user-images.githubusercontent.com/38890440/93656846-db575100-fa03-11ea-8f20-a4654730045c.png)
![Captura de tela de 2020-09-18 23-02-50](https://user-images.githubusercontent.com/38890440/93656770-389ed280-fa03-11ea-8fc4-11637d94d2a0.png)
![Captura de tela de 2020-09-18 23-02-23](https://user-images.githubusercontent.com/38890440/93656771-39376900-fa03-11ea-97ee-955cb044ee8b.png)
![Captura de tela de 2020-09-18 23-03-14](https://user-images.githubusercontent.com/38890440/93656769-376da580-fa03-11ea-9dad-7bbab5665025.png)
